### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by kalilfagundes** [mattvr/ShellGPT#12]
$ deno install -frA -n gpt https://deno.land/x/shellgpt/mod.ts
Would you like to run the above command to complete ShellGPT installation?
(y)es [default]
(n)o
leave blank to use default

> y

error: Uncaught (in promise) NotFound: program not found
  const command = Deno.run({
                       ^
    at opRun (ext:runtime/40_process.js:50:14)
    at Object.run (ext:runtime/40_process.js:136:15)
    at install (https://deno.land/x/shellgpt@0.3.3/lib/update.ts:146:24)
    at https://deno.land/x/shellgpt@0.3.3/install.ts:61:22
    at eventLoopTick (ext:core/01_core.js:183:11)

**Comment by mattvr** [comment]
Are you on Windows? You could manually run the command there `deno install -frA -n gpt https://deno.land/x/shellgpt/mod.ts` to see if that works as a workaround.

**Comment by fakoua** [comment]
Same error here (window)

**Comment by mattvr** [comment]
Hey, I just pushed a potential fix in [0.3.6](https://github.com/mattvr/ShellGPT/releases/tag/0.3.6). If you have the time, let me know if it works. @fakoua @kalilfagundes
